### ISSUE TITLE
Cookie notice?

### ISSUE THREAD

**Issue by LaMpiR** [qtranslate/qtranslate-xt#1069]
Hi.

Can somebody recommend me some plugin for the Cookie Notice, since I am using Complianz and they are awesome, but they do not support QTranslate-xt at the moment, since the plugin is not in the wordpress directory.

I have issue with them that cookie banner jumps out on every page.

**Comment by isoph** [comment]
Hi,

This might not help you much but I use Complianz | GDPR/CCPA Cookie Consent on a site with qTranslate-XT and I do not experience the banner being displayed on every page.

**Comment by LaMpiR** [comment]
What else could it be then :/

**Comment by dbalconi** [comment]
To anyone who want to add complianz compatibility with qTranslateXt you can use the standard string shortcode `[:en]english text[:it]Italian text[:]`

and then adding this in your theme function.php

```
add_filter('cmplz_cookie_settings','filtra_dati_complianz',10,1);
function filtra_dati_complianz($opzioni){
    $keys = array(
        'view_preferences',
        'save_preferences',
        'accept_all',
        'message_optin',
        'accept',
        'revoke',
        'dismiss',
        'readmore_optin',

        'categories',
    );
   foreach($keys as $key){
       if(isset($opzioni[$key])){
           $opzioni[$key] = __($opzioni[$key]);
       }
   }
    return $opzioni;
}
```

**Comment by LaMpiR** [comment]
Thank you for that. 

I have added the code and I still experience the problem.

I have two languages. When in first language(default one), I get the notice once and that is it.
When I use the second language, I get the notice. After that when ever I open an article in the second language, I keep getting the notice, so basically every move on the website is followed with a notice.

**Comment by dbalconi** [comment]
to be clear, the code written above is for the multilingual compatibility, to be able to insert the message in two different language. It does nothing for the plugin that keep appearing

**Comment by LaMpiR** [comment]
I got that later on.
My problem is still here and I am getting no help on resolving it, for months now.

**Comment by isoph** [comment]
Thanks @dbalconi for this code snippet, it works just fine!

**Comment by isoph** [comment]
@LaMpiR I just got this bug but only on my production site, not on the dev version. This meant it was not a Qtranslate XT issue but a Complianz issue. I contacted Complianz support and they quickly advised me to :  
- Purge/clear the cache of any active caching plugins on the site
- Check the site in a private browsing window
And indeed the problem was solved…

**Comment by isoph** [comment]
@dbalconi The filter you hooked on has sadly been deprecated. Version 6.0 of the plugin is thus not translatable using this code snippet.

**Comment by renad** [comment]
Hi @dbalconi,
I tried your code for Complianz translation - I added it to into theme function.php
Unfortunately, it doesn't work - see attachment.
I use the The7 template – with child theme, I added the code to the child theme as usual.

Can you help me 
![Safari](https://user-images.githubusercontent.com/1554402/161625264-a9b18c99-f21f-494c-bfad-639ad43272a1.jpg)
?

**Comment by dbalconi** [comment]
Probably is the version 6.x  of complianz , try to do a test with complianz 5.xInviato dal mio Galaxy
-------- Messaggio originale --------Da: renad ***@***.***> Data: 04/04/22  22:20  (GMT+01:00) A: qtranslate/qtranslate-xt ***@***.***> Cc: dbalconi ***@***.***>, Mention ***@***.***> Oggetto: Re: [qtranslate/qtranslate-xt] Cookie notice? (#1069) 

Hi @dbalconi,

I tried your code for Complianz translation - I added it to into theme function.php

Unfortunately, it doesn't work - see attachment.

I use the The7 template – with child theme, I added the code to the child theme as usual.

Can you help me



?

**Comment by renad** [comment]
Thanks for the advice, yes this is the Complianz version 6.1.2
So I'm going to try it with version 5, if I find it somewhere :-)

**Comment by renad** [comment]
I couldn't find Complianz v.5, and I don't even want to downgrade, I don't think that's the solution, I'd rather have a new code found :-)

**Comment by renad** [comment]
Would you be willing to update your code for version 6?
I will be happy to contribute financially …

Dusan

**Comment by dbalconi** [comment]
Sorry , I'm not interested at the moment . If for whatever reason I ll need this code for me il write it and post here . Probably the solution for V6 is very similar to mine with the hook name changed Inviato dal mio Galaxy
-------- Messaggio originale --------Da: renad ***@***.***> Data: 05/04/22  13:20  (GMT+01:00) A: qtranslate/qtranslate-xt ***@***.***> Cc: dbalconi ***@***.***>, Mention ***@***.***> Oggetto: Re: [qtranslate/qtranslate-xt] Cookie notice? (#1069) 

Would you be willing to update your code for version 6?

I will be happy to contribute financially …



Dusan

**Comment by renad** [comment]
OKI, thanks for now ...

**Comment by renad** [comment]
One more question:
Did you mean this hook names ?

**Comment by renad** [comment]
Hi,
Here is the code for the Complianz 6 version that works for me :-)

`add_filter('cmplz_cookiebanner_settings','filter_data_complianz',10,1);
function filter_data_complianz($options){
    $keys = array(
    'header',
'accept_optin',
'accept_optout',
'manage_consent',
'manage_options',
'save_settings',
'dismiss',
'message_optout',
'message_optin',
'category_functional',
'category_preferences',
'category_statistics',
'functional_text',
'statistics_text',
'statistics_text_anonymous',
'preferences_text',
'marketing_text',
'category_marketing',
'position',
'use_categories',
    );
   foreach($keys as $key){
       if(isset($options[$key])){
           $options[$key] = __($options[$key]);
       }
   }
    return $options;
}`

**Comment by bagaweb** [comment]
Thanks @renad

**Comment by bagaweb** [comment]
Actually I've just noted there are a bunch of PHP warings when using your code:

Warning: Illegal offset type in isset or empty in wp-includes\pomo\translations.php on line 91

**Comment by renad** [comment]
Try this code:

<?php defined( 'ABSPATH' ) or die();
/**
 * Make options translatable in qtranslate
 * @param array $options
 *
 * @return array
 */
function cmplz_qtranslatex_options($options){
	$keys = array(
		'header',
		'categories',
		'accept_optin',
		'accept_optout',
		'manage_consent',
		'manage_options',
		'save_settings',
		'dismiss',
		'message_optout',
		'message_optin',
		'category_functional',
		'category_preferences',
		'category_statistics',
		'functional_text',
		'statistics_text',
		'statistics_text_anonymous',
		'preferences_text',
		'marketing_text',
		'category_marketing',
	);

	foreach($keys as $key){
		if(isset($options[$key])){
			$options[$key] = __($options[$key]);
		}
	}
	return $options;
}
add_filter('cmplz_cookiebanner_settings_html','cmplz_qtranslatex_options',10,1);

**Comment by renad** [comment]
<?php defined( 'ABSPATH' ) or die();
/**
 * Make options translatable in qtranslate
 * @param array $options
 *
 * @return array
 */
function cmplz_qtranslatex_options($options){
	$keys = array(
		'header',
		'categories',
		'accept_optin',
		'accept_optout',
		'manage_consent',
		'manage_options',
		'save_settings',
		'dismiss',
		'message_optout',
		'message_optin',
		'category_functional',
		'category_preferences',
		'category_statistics',
		'functional_text',
		'statistics_text',
		'statistics_text_anonymous',
		'preferences_text',
		'marketing_text',
		'category_marketing',
	);

	foreach($keys as $key){
		if(isset($options[$key])){
			$options[$key] = __($options[$key]);
		}
	}
	return $options;
}
add_filter('cmplz_cookiebanner_settings_html','cmplz_qtranslatex_options',10,1);

**Comment by bagaweb** [comment]
Same as before unfortunately :(

**Comment by bagaweb** [comment]
I've just found out qTranslate-XT & Complianz do not work together on PHP 8.1.
They throw a critical error:

_PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /wp-includes/pomo/translations.php:91_

qTranslate-XT without Complianz works fine.
Complianz without qTranslate-XT works fine.
qTranslate-XT & Complianz work fine together on PHP 7.4.

**Comment by extremecarver** [comment]
I'm having the same problem - as soon as I activate both Complianz and Qtranslate-XT it goes havoc - each on it's own is okay. I get the following errors:

With functions.php adapted - either it doesn't do anything or I get things like:
Fatal error: Cannot redeclare cmplz_qtranslatex_options() (previously declared in /var/www/openmtbmap.org/htdocs/wp-content/plugins/complianz-gdpr/integrations/plugins/qtranslate.php:8) in /var/www/openmtbmap.org/htdocs/wp-content/themes/theme-coder/functions.php on line 55



--- Without functions.php many pictures do not load, the complianz popup doesn't load, the qtranslate languaage choser doesn't load and so on - plus I get on header:
Warning: Undefined array key "pngfix_selectors" in /var/www/openmtbmap.org/htdocs/wp-content/themes/atahualpa/functions.php on line 858


And
in footer
Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in /var/www/openmtbmap.org/htdocs/wp-includes/pomo/translations.php:91 Stack trace: #0 /var/www/openmtbmap.org/htdocs/wp-includes/pomo/translations.php(106): Translations->translate_entry() #1 /var/www/openmtbmap.org/htdocs/wp-includes/l10n.php(186): Translations->translate() #2 /var/www/openmtbmap.org/htdocs/wp-includes/l10n.php(297): translate() #3 /var/www/openmtbmap.org/htdocs/wp-content/plugins/complianz-gdpr/integrations/plugins/qtranslate.php(33): __() #4 /var/www/openmtbmap.org/htdocs/wp-includes/class-wp-hook.php(309): cmplz_qtranslatex_options() #5 /var/www/openmtbmap.org/htdocs/wp-includes/plugin.php(191): WP_Hook->apply_filters() #6 /var/www/openmtbmap.org/htdocs/wp-content/plugins/complianz-gdpr/cookiebanner/class-cookiebanner.php(1039): apply_filters() #7 /var/www/openmtbmap.org/htdocs/wp-content/plugins/complianz-gdpr/cookie/class-cookie-admin.php(1831): CMPLZ_COOKIEBANNER->get_html_settings() #8 /var/www/openmtbmap.org/htdocs/wp-includes/class-wp-hook.php(307): cmplz_cookie_admin->cookiebanner_html() #9 /var/www/openmtbmap.org/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #10 /var/www/openmtbmap.org/htdocs/wp-includes/plugin.php(476): WP_Hook->do_action() #11 /var/www/openmtbmap.org/htdocs/wp-includes/general-template.php(3058): do_action() #12 /var/www/openmtbmap.org/htdocs/wp-content/themes/atahualpa/footer.php(110): wp_footer() #13 /var/www/openmtbmap.org/htdocs/wp-includes/template.php(770): require_once('...') #14 /var/www/openmtbmap.org/htdocs/wp-includes/template.php(716): load_template() #15 /var/www/openmtbmap.org/htdocs/wp-includes/general-template.php(92): locate_template() #16 /var/www/openmtbmap.org/htdocs/wp-content/themes/atahualpa/index.php(66): get_footer() #17 /var/www/openmtbmap.org/htdocs/wp-includes/template-loader.php(106): include('...') #18 /var/www/openmtbmap.org/htdocs/wp-blog-header.php(19): require_once('...') #19 /var/www/openmtbmap.org/htdocs/index.php(17): require('...') #20 {main} thrown in /var/www/openmtbmap.org/htdocs/wp-includes/pomo/translations.php on line 91

**Comment by extremecarver** [comment]
I can solve most problems by disabling the custom css in all fields of Complianz - it still havocs my payement processor (Stripe) credit card field so I am back to 7.4 PHP if I want to activate Complianz for right now - will look if there is something more to debug/circumvent so that it is possible to activate PHP 8.x

**Comment by sviluppomania** [comment]
Activating the qTranslate plugin integration within the Complianz plugin causes a critical error.

The solution is explained here: https://wordpress.org/support/topic/qtranslate-xt-plugin/#post-16001827

**Comment by rlankhorst** [comment]
regarding php 8 compatibility, in the integration, please replace 
```
if( isset($options[$key]) ){
	$options[$key] = __($options[$key]);
}
```
with

```
if( isset($options[$key]) && is_string( $options[$key]) ){
	$options[$key] = __($options[$key]);
}
```

See
https://wordpress.org/support/topic/qtranslate-xt-plugin/

**Comment by bagaweb** [comment]
Excellent thanks @rlankhorst

**Comment by extremecarver** [comment]
I still have a lot of problems if enabling 8.0 or 8.1 with both qtranslate xt and complianz. The change just made the page not crash - but still behave problematic (broken layout mainly, some other plugins going crazy).

**Comment by rlankhorst** [comment]
Complianz is tested with php 8 & 8.1. It sounds as if your other plugins, including qtranslate, are not ready for php 8/8.1

Looking at the logs, Wordpress core also isn't.

**Comment by sviluppomania** [comment]
> Hi @dbalconi, I tried your code for Complianz translation - I added it to into theme function.php Unfortunately, it doesn't work - see attachment. I use the The7 template – with child theme, I added the code to the child theme as usual.
> 
> Can you help me ![Safari](https://user-images.githubusercontent.com/1554402/161625264-a9b18c99-f21f-494c-bfad-639ad43272a1.jpg) ?

@rlankhorst

**Comment by dbalconi** [comment]
My code doesn't work with compianz 6.x
-------- Messaggio originale --------Da: sviluppomania ***@***.***> Data: 13/09/22  18:18  (GMT+01:00) A: qtranslate/qtranslate-xt ***@***.***> Cc: dbalconi ***@***.***>, Mention ***@***.***> Oggetto: Re: [qtranslate/qtranslate-xt] Cookie notice? (#1069) 



Hi @dbalconi, I tried your code for Complianz translation - I added it to into theme function.php Unfortunately, it doesn't work - see attachment. I use the The7 template – with child theme, I added the code to the child theme as usual.

Can you help me  ?



@rlankhorst

**Comment by extremecarver** [comment]
> Complianz is tested with php 8 & 8.1. It sounds as if your other plugins, including qtranslate, are not ready for php 8/8.1
> 
> Looking at the logs, Wordpress core also isn't.


wordpress seems fine with 8.0  - but yes thowring some errors in console in 8.1 - but my site is fine. It's only if I actiave BOTH Complianz and Q-Translate XT at the same time that I get problems. Either plugin alone and I*m fine. And yes I did change the code in the integration. Actually no difference between 8.0 and 8.1 in real life (in console 8.1 looks more problematic).

**Comment by extremecarver** [comment]
Sorry - actually I think the bug is solved for me too. However Complianz on PHP 8.0 or later does not work with my theme. I just completely removed the qtranslate.php plugin of complianz then noticed this problem.

**Comment by rlankhorst** [comment]
Made some adjustments, this branch seems to work for all fields

https://github.com/Really-Simple-Plugins/complianz-gdpr/pull/377
