### ISSUE TITLE
Fatal error: Uncaught TypeError: Cannot access offset of type string

### ISSUE THREAD

**Issue by l1z0b** [qtranslate/qtranslate-xt#1402]
After updating my server from PHP 7.4 to PHP 8.2 I receive the following error:

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in web/wp-content/plugins/qtranslate-xt/src/language_blocks.php:439

Stack trace:
#0 web/wp-content/plugins/qtranslate-xt/src/frontend.php(445): qtranxf_use_content() 
#1 web/wp-content/plugins/qtranslate-xt/src/frontend.php(480): qtranxf_translate_object_property() 
#2 web/wp-content/plugins/qtranslate-xt/src/frontend.php(508): qtranxf_translate_post() 
#3 web/wp-includes/class-wp-hook.php(324): qtranxf_postsFilter() 
#4 web/wp-includes/plugin.php(256): WP_Hook->apply_filters() 
#5 web/wp-includes/class-wp-query.php(3530): apply_filters_ref_array() 
#6 web/wp-includes/class-wp-query.php(3824): WP_Query->get_posts() 
#7 web/wp-includes/post.php(6118): WP_Query->query() 
#8 web/wp-includes/post-template.php(719): get_pages() 
#9 web/wp-includes/post-template.php(620): get_body_class() 
#10 web/wp-content/themes/hotelbramante/header.php(280): body_class() 
#11 web/wp-includes/template.php(790): require_once('...') 
#12 web/wp-includes/template.php(725): load_template() 
#13 web/wp-includes/general-template.php(48): locate_template()
#14 web/wp-content/themes/hotelbramante/page-homepage.php(3): get_header() 
#15 web/wp-includes/template-loader.php(106): include('...') 
#16 web/wp-blog-header.php(19): require_once('...') 
#17 web/index.php(17): require('...')
#18 {main} thrown in **web/wp-content/plugins/qtranslate-xt/src/language_blocks.php on line 439**

My website has Wordpress 6.4.3, I can't find how to fix this problem, before the PHP update everything worked fine.

**Comment by herrvigg** [comment]
In 3.15.2 this is the line https://github.com/qtranslate/qtranslate-xt/blob/7c89d2514f9833184e70322a292d149022736fe5/src/language_blocks.php#L439C4-L439C99
```
    if ( preg_match( '/%LANG:([^:]*):([^%]*)%/', $q_config['not_available'][ $lang ], $match ) ) {
```
The error seems to say the global `$q_config` has become a string, which doesn't make sense.
Are you able to reproduce this error?
